### ISSUE TITLE
Error producing PDF. ! Undefined control sequence. <argument> ... \hspace {\z@ }\ignorespaces \color     {lightgray}\tiny {[1]}\end... l.65 \paragraphnumber{[1]}

### ISSUE THREAD

**Issue by ghost** [cysouw/count-para#1]
The other day this error message was output:

```
Error producing PDF.
! Undefined control sequence.
<argument> ... \hspace {\z@ }\ignorespaces \color
                                                  {lightgray}\tiny {[1]}\end...
l.65 \paragraphnumber{[1]}
```

I had some error messages in the past which were usually due to missing squared brackets. I resolved the error by using --trace and checked where parsing was slowing down (that is where the brackets were missing), but this time --trace does not provide any hints.

I searched for the error message on the web but found no hints.

I can convert the document from .md to .pdf using Pandoc with no issue; that is the command I use:

`$ pandoc file.md --pdf-engine=xelatex -o file.pdf`

But when I add count-para.lua filter:

`$ pandoc file.md --pdf-engine=xelatex --lua-filter=count-para.lua -o file.pdf
`

I get the error message mentioned above.

Trisquel GNU/Linux 10.0.1
pandoc 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.7.7

Do you have any hint of how I could troubleshoot or fix this?

**Comment by cysouw** [comment]
good catch. I added the dependency 'xcolor' for Latex. Maybe in the future I add an option of the color, but for now I like to keep it as simple as possible.
